---
name: Dokku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Git HTTPS push deploy
        uses: ilkka/git-https-push-action@v1.1.0
        with:
          remoteUrl: '${{ secrets.PUSH_REMOTE }}/imd2-frontend-angular'
          skipHooks: false
          
      - name: Notify
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.pushcut.io/v1/notifications/github_deploy_done?title=Deploy successfull&text=Master branch of imd2-frontend-angular applicaton was successfully deployed to dokku!'
          method: 'POST'
          customHeaders: "{\"API-key\": \"${{ secrets.PUSHCUT_API_KEY }}\"}"
